const http = require('http');
const { spawn } = require('child_process');
const fs = require('fs');
const path = require('path');

const ARTIFACTS_DIR = 'C:\\Users\\Varchive\\.gemini\\antigravity-ide\\brain\\43accb94-1c03-42f9-80a3-274f67f37436';
const CHROME_PATH = 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
const PORT = 9333;

async function sleep(ms) {
  return new Promise(r => setTimeout(r, ms));
}

function getJson(url) {
  return new Promise((resolve, reject) => {
    http.get(url, res => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try { resolve(JSON.parse(data)); }
        catch (e) { reject(e); }
      });
    }).on('error', reject);
  });
}

async function main() {
  console.log("Launching Chrome headless with remote debugging on port", PORT);
  const userDataDir = path.join(ARTIFACTS_DIR, 'scratch', 'chrome_temp_' + Date.now());
  fs.mkdirSync(userDataDir, { recursive: true });

  const chromeProc = spawn(CHROME_PATH, [
    `--remote-debugging-port=${PORT}`,
    `--user-data-dir=${userDataDir}`,
    '--headless=new',
    '--disable-gpu',
    '--no-first-run',
    '--window-size=1280,900'
  ], { stdio: 'ignore' });

  process.on('exit', () => {
    try { chromeProc.kill(); } catch (e) {}
  });

  // Wait for Chrome CDP to be available
  let version = null;
  for (let i = 0; i < 30; i++) {
    await sleep(500);
    try {
      version = await getJson(`http://127.0.0.1:${PORT}/json/version`);
      if (version && version.webSocketDebuggerUrl) break;
    } catch (e) {}
  }

  if (!version || !version.webSocketDebuggerUrl) {
    console.error("Failed to connect to Chrome remote debugging.");
    process.exit(1);
  }

  console.log("Connected to Chrome! Browser WS:", version.webSocketDebuggerUrl);
  const targets = await getJson(`http://127.0.0.1:${PORT}/json/list`);
  const pageTarget = targets.find(t => t.type === 'page');
  const wsUrl = pageTarget.webSocketDebuggerUrl;

  const ws = new WebSocket(wsUrl);
  let idCounter = 1;
  const pending = new Map();

  ws.onmessage = (event) => {
    const msg = JSON.parse(event.data);
    if (msg.id && pending.has(msg.id)) {
      const { resolve, reject } = pending.get(msg.id);
      pending.delete(msg.id);
      if (msg.error) reject(msg.error);
      else resolve(msg.result);
    }
  };

  await new Promise(r => ws.onopen = r);

  function send(method, params = {}) {
    return new Promise((resolve, reject) => {
      const id = idCounter++;
      pending.set(id, { resolve, reject });
      ws.send(JSON.stringify({ id, method, params }));
    });
  }

  async function evaluate(expression) {
    const res = await send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true });
    return res.result ? res.result.value : null;
  }

  async function captureScreenshot(filename) {
    const res = await send('Page.captureScreenshot', { format: 'png' });
    const buffer = Buffer.from(res.data, 'base64');
    const outPath = path.join(ARTIFACTS_DIR, filename);
    fs.writeFileSync(outPath, buffer);
    console.log(`[SCREENSHOT] Saved: ${outPath}`);
    return outPath;
  }

  await send('Page.enable');
  await send('Runtime.enable');
  await send('DOM.enable');

  console.log("\n--- STEP 1: Logging in as Faculty ---");
  await send('Page.navigate', { url: 'http://localhost/sti-activity-system/auth/login.php' });
  await sleep(1500);

  await evaluate(`
    document.querySelector('[name="email"]').value = 'faculty@sti.edu';
    document.querySelector('[name="password"]').value = 'password';
    document.querySelector('form').submit();
  `);
  await sleep(2000);

  console.log("\n--- STEP 2: Navigating to proposal-create.php ---");
  await send('Page.navigate', { url: 'http://localhost/sti-activity-system/faculty/proposal-create.php' });
  await sleep(2000);

  const initialCheck = await evaluate(`({
    themeVal: document.getElementById('f1_theme').value,
    hasSuggestBtn: !!document.getElementById('btnSuggestTheme'),
    statusText: document.getElementById('themeAiStatus')?.innerText.trim()
  })`);
  console.log("Initial Form State:", initialCheck);

  console.log("\n--- STEP 3: Typing Activity Title ---");
  const testTitle = "TechNovation 2026: STI Student Hackathon";
  await evaluate(`
    const titleEl = document.getElementById('f1_title');
    titleEl.value = '${testTitle}';
    titleEl.dispatchEvent(new Event('input', { bubbles: true }));
  `);

  console.log("Title entered. Waiting for debounced automatic AI generation (approx 4-6s)...");
  let autoGeneratedTheme = '';
  for (let i = 0; i < 30; i++) {
    await sleep(500);
    const check = await evaluate(`({
      themeVal: document.getElementById('f1_theme').value,
      statusText: document.getElementById('themeAiStatus')?.innerText.trim()
    })`);
    if (check.themeVal) {
      autoGeneratedTheme = check.themeVal;
      console.log(`Auto-generated Theme Detected: "${autoGeneratedTheme}"`);
      console.log(`Status message: "${check.statusText}"`);
      break;
    }
  }

  await sleep(1000);
  await captureScreenshot('theme_auto_generated.png');

  console.log("\n--- STEP 4: Manually Editing the Theme ---");
  await evaluate(`
    const themeEl = document.getElementById('f1_theme');
    themeEl.value = themeEl.value + ' - Empowering Young Coders';
    themeEl.dispatchEvent(new Event('input', { bubbles: true }));
  `);
  await sleep(500);

  const editedCheck = await evaluate(`({
    themeVal: document.getElementById('f1_theme').value,
    statusText: document.getElementById('themeAiStatus')?.innerText.trim()
  })`);
  console.log("After Manual Edit:", editedCheck);

  console.log("\n--- STEP 5: Changing Title to Test Overwrite Protection ---");
  const newTitle = "TechNovation 2026: Cyber Security & Cloud Summit";
  await evaluate(`
    const titleEl = document.getElementById('f1_title');
    titleEl.value = '${newTitle}';
    titleEl.dispatchEvent(new Event('input', { bubbles: true }));
  `);
  console.log("Waiting 3 seconds to verify manually edited theme is NOT overwritten...");
  await sleep(3000);

  const preservedCheck = await evaluate(`({
    themeVal: document.getElementById('f1_theme').value,
    statusText: document.getElementById('themeAiStatus')?.innerText.trim()
  })`);
  console.log("Overwrite Protection Check:", preservedCheck);
  await captureScreenshot('theme_manual_edit_preserved.png');

  console.log("\n--- STEP 6: Testing Update Theme with AI ---");
  await evaluate(`
    forceRegenerateTheme();
  `);
  console.log("Force regenerate clicked. Waiting for updated AI theme...");
  for (let i = 0; i < 30; i++) {
    await sleep(500);
    const check = await evaluate(`({
      themeVal: document.getElementById('f1_theme').value,
      statusText: document.getElementById('themeAiStatus')?.innerText.trim()
    })`);
    if (check.themeVal && check.themeVal !== preservedCheck.themeVal) {
      console.log(`Updated AI Theme: "${check.themeVal}"`);
      console.log(`Status message: "${check.statusText}"`);
      break;
    }
  }
  await sleep(1000);
  await captureScreenshot('theme_regenerated.png');

  console.log("\n--- STEP 7: Testing Step 2 AI Objectives Auto-Generation ---");
  await evaluate(`
    document.getElementById('f1_source').value = 'student_org';
    document.getElementById('f1_start_time').value = '08:00';
    document.getElementById('f1_end_time').value = '17:00';
    document.getElementById('f1_venue').value = 'STI Auditorium';
    document.getElementById('f1_target_participants').value = '250';
    document.getElementById('f1_venue_address').value = 'STI Academic Center';
    
    // Set date to tomorrow
    const d = new Date();
    d.setDate(d.getDate() + 5);
    document.getElementById('f1_event_date').value = d.toISOString().split('T')[0];

    // Mock file input validity
    const dt = new DataTransfer();
    const file = new File(['mock image content'], 'poster.png', { type: 'image/png' });
    dt.items.add(file);
    document.getElementById('f1_poster_file').files = dt.files;

    nextStep();
  `);

  console.log("Navigated to Step 2. Waiting for Objectives auto-generation...");
  let objectivesGenerated = false;
  for (let i = 0; i < 30; i++) {
    await sleep(500);
    const objCheck = await evaluate(`({
      genObj: document.getElementById('f2_general_objectives').value,
      specObj: document.getElementById('f2_specific_objectives').value
    })`);
    if (objCheck.genObj && objCheck.specObj) {
      console.log("AI Objectives Generated Successfully!");
      console.log("General Objective:", objCheck.genObj.substring(0, 100) + '...');
      objectivesGenerated = true;
      break;
    }
  }
  await sleep(1000);
  await captureScreenshot('objectives_auto_generated.png');

  ws.close();
  chromeProc.kill();
  console.log("\n=======================================================");
  console.log("ALL BROWSER VERIFICATION TESTS COMPLETED SUCCESSFULLY!");
  console.log("=======================================================");
}

main().catch(err => {
  console.error("Browser verification failed:", err);
  process.exit(1);
});
